{"pypowervm": "1.1.24", "lxml": "4.6.3", "oslo-concurrency": "4.4.0", "fasteners": "0.16.3", "six": "1.16.0", "oslo-config": "8.7.0", "debtcollector": "2.2.0", "pbr": "5.6.0", "wrapt": "1.12.1", "importlib-metadata": "4.6.0", "typing-extensions": "3.10.0.0", "zipp": "3.4.1", "netaddr": "0.8.0", "oslo-i18n": "5.0.1", "pyyaml": "5.4.1", "requests": "2.25.1", "certifi": "2021.5.30", "chardet": "4.0.0", "idna": "2.10", "urllib3": "1.26.6", "rfc3986": "1.5.0", "stevedore": "3.3.0", "oslo-utils": "4.9.1", "iso8601": "0.1.14", "netifaces": "0.11.0", "packaging": "20.9", "pyparsing": "2.4.7", "pytz": "2021.1", "oslo-context": "3.3.0", "oslo-log": "4.5.0", "oslo-serialization": "4.1.0", "msgpack": "1.0.2", "pyinotify": "0.9.6", "python-dateutil": "2.8.1", "pyasn1": "0.4.8", "pyasn1-modules": "0.2.8", "taskflow": "4.6.0", "automaton": "2.3.0", "prettytable": "2.1.0", "wcwidth": "0.2.5", "cachetools": "4.2.2", "futurist": "2.3.0", "jsonschema": "3.2.0", "attrs": "21.2.0", "pyrsistent": "0.18.0", "setuptools": "57.0.0", "networkx": "2.5.1", "decorator": "4.4.2", "pydot": "1.4.2", "tenacity": "7.0.0"}